### ISSUE TITLE
Bug retrieving incorrect value

### ISSUE THREAD

**Issue by gamax92** [katlogic/ljx#4]
```
local function bug()
    local var=9
    local a=setmetatable({},{
        __index=function(t,i)
            return setmetatable({},{
                __len=function() return var end
            })
        end
    })
    print(var, #a.a)
end
bug()
```

What's expected is `9, 9` But instead you get out `9, table: 0xADDRESS`
The table itself appears to be _ENV

**Comment by katlogic** [comment]
Workaround for now:

Run with -O-llift. This is one of the numerous bugs in FNEW elimination, so it will take a while. Thanks for reporting.
